[package]
name = "rain-pyth"
version = "0.1.1"

[profile.default]
libs = ["dependencies"]

solc = "0.8.25"


fs_permissions = [
  { access = "read-write", path = "src/generated" },
  { access = "read-write", path = "meta" },
]

evm_version = "cancun"

optimizer = true
optimizer_runs = 1000

bytecode_hash = "none"
cbor_metadata = false

[dependencies]
"rainlang-interface" = "0.2.8"
"forge-std" = "1.16.2"
"@openzeppelin-contracts" = "5.6.1"
"@pythnetwork-pyth-sdk-solidity" = "4.3.1"
"rainlang" = "0.2.1"
"rain-metadata" = "0.1.0"
"rain-sol-codegen" = "0.1.36"
"rain-math-float" = "0.1.1"
"rain-lib-typecast" = "0.1.0"
"rain-deploy" = "0.1.7"
"rain-extrospection" = "0.1.14"
"rain-intorastring" = "0.1.0"
"rain-lib-hash" = "0.1.0"
"rain-lib-memkv" = "0.1.0"
"rain-math-binary" = "0.1.4"
"rain-solmem" = "0.1.28"
"rain-string" = "0.2.0"
"rain-tofu-erc20-decimals" = "0.1.1"

[soldeer]
recursive_deps = false
